Repository konflux-ci/docs, pull requests merged in 2024-05, with the labels that each got.

#18 Update index.adoc
  docs/modules/ROOT/pages/getting-started/index.adoc
Labels: size: M

#19 Why Konflux?
  docs/modules/ROOT/pages/discover/index.adoc
Labels: size: L

#14 Releasing an application
  docs/modules/ROOT/images/managed_environment.png
  docs/modules/ROOT/pages/advanced-how-tos/releasing/index.adoc
Labels: size: M

#22 Adding SLSA conformity
  docs/modules/ROOT/pages/discover/slsa-conformity.adoc
Labels: size: XXL

#21 Update cli.adoc
  docs/modules/ROOT/pages/getting-started/cli.adoc
Labels: size: XL, size: L

#27 Moved content for integration tests
  docs/modules/ROOT/pages/how-tos/testing/integration/adding.adoc
Labels: size: XXL, size: L

#25 Preventing redundant builds
  docs/modules/ROOT/pages/how-tos/configuring/redundant-rebuilds.adoc
Labels: size: XL

#28 Added content for Creating a custom integration test for upstream
  docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc
Labels: size: XXL

#20 Added Configuring Applications and Components as Code with Kustomize
  docs/modules/ROOT/pages/how-tos/configuring/configuration-as-code.adoc
Labels: size: XXL

#32 Update customizing-the-build.adoc
  docs/modules/ROOT/pages/how-tos/configuring/customizing-the-build.adoc
Labels: size: XXL

#34 Update index.adoc
  docs/modules/ROOT/pages/how-tos/testing/index.adoc
Labels: size: L

#36 Update index.adoc
  docs/modules/ROOT/pages/how-tos/testing/index.adoc
Labels: size: S

#26 Managing multiple software versions
  docs/modules/ROOT/pages/advanced-how-tos/managing-multiple-versions.adoc
Labels: size: XXL

#37 Update component-nudges.adoc
  docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc
Labels: size: XL, size: L

#30 Update creating.adoc
  docs/modules/ROOT/pages/how-tos/creating.adoc
Labels: size: XXL, size: XL

#41 Split creating doc into two docs
  .vscode/settings.json
  docs/modules/ROOT/pages/advanced-how-tos/_nav.adoc
  docs/modules/ROOT/pages/advanced-how-tos/installing/enabling-builds.adoc
  docs/modules/ROOT/pages/advanced-how-tos/installing/index.adoc
  docs/modules/ROOT/pages/how-tos/creating.adoc
Labels: size: L

#33 Creating secrets
  docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
Labels: size: XL, size: L

#39 Updated Deleting application
  docs/modules/ROOT/images/more.png
  docs/modules/ROOT/pages/how-tos/deleting.adoc
Labels: size: L

#48 Add more Build service secrets lookup options
  docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
Labels: size: L

#50 Update _nav.adoc
  docs/modules/ROOT/pages/how-tos/_nav.adoc
  docs/modules/ROOT/pages/how-tos/testing/overview.adoc
Labels: size: XS, size: S
