Repository konflux-ci/docs, pull requests merged in 2024-06, with the labels that each got.

#55 Revert "Updated antora settings"
  docs/antora.yml
  docs/modules/ROOT/pages/discover/_nav.adoc
  docs/modules/ROOT/pages/discover/index.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: size: XL

#38 Updated build time tests
  docs/modules/ROOT/pages/how-tos/testing/build/index.adoc
  docs/modules/ROOT/pages/how-tos/testing/build/snyk.adoc
Labels: size: XXL, size: XL

#40 Update build-definitions references to new org
  docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
  docs/modules/ROOT/pages/how-tos/configuring/hermetic-builds.adoc
Labels: size: XS

#13 Miscellaneous fixes
  .github/workflows/labeler.yml
  .github/workflows/preview.yaml
  .github/workflows/size-label.yml
  docs/modules/ROOT/pages/how-tos/_nav.adoc
Labels: size: XXL

#52 nudges: components referenced across applications
  docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc
Labels: size: M

#49 Managing compliance with EC
  docs/modules/ROOT/pages/advanced-how-tos/managing-compliance-with-ec.adoc
Labels: size: M

#45 Update sboms.adoc
  docs/modules/ROOT/pages/how-tos/metadata/sboms.adoc
Labels: size: XXL

#53 Updated overviews
  docs/modules/ROOT/pages/advanced-how-tos/releasing/index.adoc
Labels: size: S

#51 HACDOCS-941-glossary
  docs/modules/ROOT/pages/glossary/index.adoc
Labels: size: XL

#43 Adding the contributing guide
  CONTRIBUTING.md
  docs/modules/ROOT/pages/contribute/index.adoc
Labels: size: XL, size: L

#35 Managing a security fix
  docs/modules/ROOT/pages/advanced-how-tos/managing-security-fix.adoc
Labels: size: XXL

#24 Prefetching dependencies
  docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
Labels: size: XXL
